### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by AkshJain99** [theAayushbajaj/Social-Media-Sentiment-Analysis#6]
HI actually while building your project I am facing error while running server 
It is showing that 

ckey = open("ckey.txt","r").read()
csecret = open("csecret.txt","r").read()
atoken = open("atoken.txt","r").read()
asecret = open("asecret.txt","r").read()

these file ckey.txt, csecret.txt, etc they doesnt exist 
sp from i get these files?

**Comment by theAayushbajaj** [comment]
you need to sign-up for the twitter developer account for tweepy API access. You'll get the following keys from there
